tap "azure/functions"
tap "jesseduffield/lazygit"
# Generic-purpose lossless compression algorithm by Google
brew "brotli"
# Library and utilities for processing GIFs
brew "giflib"
# Performance-portable, length-agnostic SIMD with runtime dispatch
brew "highway"
# Library of 2D and 3D vector, matrix, and math operations
brew "imath"
# JPEG image codec that aids compression and decompression
brew "jpeg-turbo"
# Library for manipulating PNG images
brew "libpng"
# Extremely Fast Compression algorithm
brew "lz4"
# General-purpose data compression with high compression ratio
brew "xz"
# Zstandard is a real-time compression algorithm
brew "zstd"
# TIFF library and utilities
brew "libtiff"
# Color management engine supporting ICC profiles
brew "little-cms2"
# High dynamic-range image file format
brew "openexr"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Perceptual video quality assessment based on multi-method fusion
brew "libvmaf"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Apache Portable Runtime library
brew "apr"
# Mozilla CA certificate store
brew "ca-certificates"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# C string library for manipulating Unicode strings
brew "libunistring"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Distributed revision control system
brew "git"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Macro processing language
brew "m4"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# NaCl networking and cryptography library
brew "libsodium"
# YAML Parser
brew "libyaml"
# Library for decimal floating point arithmetic
brew "mpdecimal"
# Library for command-line editing
brew "readline"
# Command-line interface for SQLite
brew "sqlite"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# High performance key/value database
brew "berkeley-db@5"
# Parser generator
brew "bison"
# Collection of portable C++ source libraries
brew "boost"
# Software library to render fonts
brew "freetype"
# XML-based font configuration API for X Windows
brew "fontconfig"
# Core application library for C
brew "glib"
# X.Org: Protocol Headers
brew "xorgproto"
# X.Org: A Sample Authorization Protocol for X
brew "libxau"
# X.Org: X Display Manager Control Protocol library
brew "libxdmcp"
# X.Org: Interface to the X Window System protocol
brew "libxcb"
# X.Org: Core X11 protocol client library
brew "libx11"
# X.Org: Library for common extensions to the X11 protocol
brew "libxext"
# X.Org: Library for the Render Extension to the X11 protocol
brew "libxrender"
# Real-time data compression library
brew "lzo"
# Low-level library for pixel manipulation
brew "pixman"
# Vector graphics library with cross-device output support
brew "cairo"
# Cross-platform make
brew "cmake"
# GNU multiple precision arithmetic library
brew "gmp"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Header-only library for parsing TOML
brew "cpptoml"
# HTTP/2 C Library
brew "libnghttp2"
# C library implementing the SSH2 protocol
brew "libssh2"
# Tool for downloading RTMP streaming media
brew "rtmpdump"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Text processing system for reStructuredText
brew "docutils"
# Binary-decimal and decimal-binary routines for IEEE doubles
brew "double-conversion"
# Open-source formatting library for C++
brew "fmt"
# Library for processing command-line flags
brew "gflags"
# Application-level logging library
brew "glog"
# Asynchronous event library
brew "libevent"
# Compression/decompression library aiming for high speed
brew "snappy"
# Collection of reusable C++ library artifacts developed at Facebook
brew "folly"
# C++14 implementation of the TLS-1.3 standard
brew "fizz"
# Modular, composable client/server abstractions framework
brew "wangle"
# Facebook's branch of Apache Thrift, including a new C++ server
brew "fbthrift"
# Thrift functions for querying information from a service
brew "fb303"
# Shared library for Watchman and Eden projects
brew "edencommon"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Smart font renderer for non-Roman scripts
brew "graphite2"
# OpenType text shaping engine
brew "harfbuzz"
# Development kit for the Java programming language
brew "openjdk"
# Database version control to control migrations
brew "flyway"
# XSL-FO print formatter for making PDF or PS documents
brew "fop"
# Implementation of the Unicode BiDi algorithm
brew "fribidi"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# GNU database manager
brew "gdbm"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# JBIG2 decoder and library (for monochrome documents)
brew "jbig2dec"
# Library for JPEG-2000 image manipulation
brew "openjpeg"
# International domain name library
brew "libidn"
# Framework for layout and rendering of i18n text
brew "pango"
# Interpreter for PostScript and PDF
brew "ghostscript"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# Common error values for all GnuPG components
brew "libgpg-error"
# Cryptographic library based on the code from GnuPG
brew "libgcrypt"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Google Testing and Mocking Framework
brew "googletest"
# Library for manipulating JPEG-2000 images
brew "jasper"
# Image manipulation
brew "netpbm"
# GNU triangulated surface library
brew "gts"
# Library to render SVG files using Cairo
brew "librsvg"
# Generic library support script
brew "libtool"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU grep, egrep and fgrep
brew "grep"
# Highly capable, feature-rich programming language
brew "perl"
# Automatically generate simple man pages
brew "help2man"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Open h.265 video codec implementation
brew "libde265"
# Database of common MIME types
brew "shared-mime-info"
# H.265/HEVC encoder
brew "x265"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# C/C++ seam carving library
brew "liblqr"
# LLVM's OpenMP runtime library
brew "libomp"
# Library for reading RAW files from digital photo cameras
brew "libraw"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# GNU utilities for networking
brew "inetutils"
# Regular expressions library
brew "oniguruma"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Environment diagnostics for Kotlin Multiplatform Mobile app development
brew "kdoctor"
# Network authentication protocol
brew "krb5"
# Simple terminal UI for git commands
brew "lazygit"
# Sophisticated file transfer program
brew "lftp"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Postgres C API library
brew "libpq", link: true
# Very basic terminfo library
brew "unibilium"
# Library for processing keyboard entry from the terminal
brew "libtermkey"
# Multi-platform support library with a focus on asynchronous I/O
brew "libuv"
# C99 library which implements a VT220 or xterm terminal emulator
brew "libvterm"
# GNOME XML library
brew "libxml2"
# C XSLT library for GNOME
brew "libxslt"
# High-performance theorem prover
brew "z3"
# Next-gen compiler infrastructure
brew "llvm"
# Parsing Expression Grammars For Lua
brew "lpeg"
# Powerful, lightweight programming language
brew "lua"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit"
# Package manager for the Lua programming language
brew "luarocks"
# Bare libuv bindings for lua
brew "luv"
# Small build system for use with gyp or CMake
brew "ninja"
# Fast and user friendly build system
brew "meson"
# Library for a binary-based efficient data interchange format
brew "msgpack"
# QUIC transport protocol implementation
brew "mvfst"
# Text-based UI library
brew "ncurses"
# Incremental parsing library
brew "tree-sitter"
# Clean C library for processing UTF-8 Unicode data
brew "utf8proc"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# Open source suite of directory software
brew "openldap"
# Fast, disk space efficient package manager
brew "pnpm"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Python version management
brew "pyenv"
# Easily download, build, install, upgrade, and uninstall Python packages
brew "python-setuptools"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# Rust toolchain installer
brew "rustup"
# Substitute for classic 'make' tool with autoconf/automake functionality
brew "scons"
# Microsoft SQL Server command-line interface
brew "sqlcmd"
# Version control system designed to be a better CVS
brew "subversion"
# Generate scripting interfaces to C/C++ code
brew "swig"
# Terminal multiplexer
brew "tmux"
# Command-line unarchiving tools supporting multiple formats
brew "unar"
# ODBC 3 connectivity for UNIX
brew "unixodbc"
# X.Org: Set of autoconf macros used to build other xorg packages
brew "util-macros"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Watch files and take action when they change
brew "watchman"
# Cross-platform C++ GUI toolkit
brew "wxwidgets"
# X.Org: X Network Transport layer shared code
brew "xtrans"
# JavaScript package manager
brew "yarn"
# Azure Functions Core Tools 4.0
brew "azure/functions/azure-functions-core-tools@4"
# Command-line interface for 1Password
cask "1password-cli"
# Enable Windows-like alt-tab
cask "alt-tab"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "jakebecker.elixir-ls"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-edgedevtools.vscode-edge-devtools"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "phoenixframework.phoenix"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "royalmist.vscode-eex-format"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
